### ISSUE TITLE
is it possible to use another stm board with this?

### ISSUE THREAD

**Issue by AliBigdeli** [pavkriz/knxduino#1]
i am going to buy a board to test your repo but is this possible to use this " STM32F103C8T6  "or any other stm?

**Comment by pavkriz** [comment]
Hello, STM32G0 is the only target now. I discuss the reasons in this thread https://hackaday.io/project/166491-knxduino/discussion-137810. You can buy [Nucleo-G071RB](https://www.st.com/content/st_com/en/products/evaluation-tools/product-evaluation-tools/mcu-mpu-eval-tools/stm32-mcu-mpu-eval-tools/stm32-nucleo-boards/nucleo-g071rb.html).

**Comment by AliBigdeli** [comment]
ok thanks
